language: python
sudo: false

matrix:
    include:
        - python: 3.5
          os: linux
          dist: xenial
          env: TOXENV=py35
        - python: pypy3
          os: linux
          dist: xenial
          env: TOXENV=pypy
        - python: 3.5
          os: linux
          dist: xenial
          env: TOXENV=flake8
    allow_failures:
    - python: pypy

install:
  - pip install -r requirements.d/development.txt
  - pip install .

script: tox moin
